server:
  port: 8060
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/rentals
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db-changelog_main.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none


springdoc:
  api-docs:
    resolve-schema-properties: true
    path: /api
  swagger-ui:
    path: /api/doc
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
